{
    "name": "OpenG2P Registry MTS Connector",
    "category": "G2P",
    "version": "17.0.0.0.0",
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "LGPL-3",
    "depends": ["mts_connector", "g2p_registry_base"],
    "data": [
        "data/cron.xml",
        "views/g2p_mts_connector.xml",
        "views/res_config_settings.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
