# Part of OpenG2P. See LICENSE file for full copyright and licensing details.

{
    "name": "G2P Registry",
    "category": "G2P",
    "version": "17.0.0.0.0",
    "sequence": 1,
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "LGPL-3",
    "depends": [
        "g2p_registry_base",
        "g2p_registry_individual",
        "g2p_registry_group",
        "g2p_registry_membership",
        "g2p_documents",
        "g2p_document_field",
        "g2p_documents_bootstrap_s3",
        "g2p_registry_documents",
        "g2p_registry_documents_group",
        "g2p_registry_documents_individual",
        "g2p_bank",
        "g2p_bank_rest_api",
        # "g2p_auth_oidc",
        # "g2p_auth_id_oidc",
        # "g2p_auth_oidc_keycloak",
        "g2p_odk_importer",
        "g2p_odk_importer_documents",
        "g2p_leaflet_map",
        "g2p_enumerator",
        "g2p_agent_portal_base",
        "g2p_registration_portal_base",
        "g2p_odk_user_mapping",
        "g2p_encryption",
        "g2p_encryption_rest_api",
        "g2p_encryption_keymanager",
        "g2p_registry_encryption",
        "g2p_document_encryption",
        "g2p_registry_document_encryption",
        "g2p_registry_document_encryption_group",
        "g2p_registry_document_encryption_individual",
        "g2p_auth_oidc_encryption",
        "g2p_openid_vci",
        "g2p_openid_vci_group",
        "g2p_openid_vci_rest_api",
        "g2p_portal_auth",
        "g2p_disable_password_login",
        "g2p_registry_rest_api",
        "g2p_registry_addl_info",
        "g2p_registry_addl_info_rest_api",
        "g2p_registry_g2p_connect_rest_api",
        "g2p_registry_datashare_websub",
        "g2p_registry_datashare_rabbitmq",
        "g2p_registry_deduplication_deduplicator",
        "g2p_superset_dashboard",
        "g2p_registry_id_deduplication",
        "g2p_registry_proxy_means_test",
        "g2p_change_management",
        "g2p_security",
        "g2p_profile_image",
        "g2p_registry_theme",
    ],
    "external_dependencies": {"python": ["python-jose"]},
    "data": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
